### ISSUE TITLE
查询地址的url是不是有问题

### ISSUE THREAD

**Issue by NeelyYu** [beergold/easyfood#2]
项目跑起来，在查地址时候会报错

**Comment by beergold** [comment]
截图有吗，我刚才跑了下，目前是正常的，
也请检查下redis是否配置

**Comment by beergold** [comment]
![image](https://user-images.githubusercontent.com/54296655/163422684-20d00b40-69c5-4695-af72-56f6472ecc95.png)

**Comment by beergold** [comment]
![image](https://user-images.githubusercontent.com/54296655/163423735-e0f25306-a8d5-4e53-a605-2b0795a89cd2.png)
![image](https://user-images.githubusercontent.com/54296655/163423745-da7d1b36-793f-4772-9198-7a8280eb06a4.png)

实测当前程序调用目前仍然正常

**Comment by NeelyYu** [comment]
是不是需要抓包自己的查询地址url
![image](https://user-images.githubusercontent.com/31427858/163424868-9db2b19c-24c4-462d-a055-1dd462640892.png)

**Comment by beergold** [comment]
需要抓包自己的userId，和 token
因为登录过程app有签名参与，小程序段微信也有自己的安全机制默认是sha(sessionKey+一些规则)
所以token目前暂时还需要自己抓包获取，这个也在文档中特殊表明过
只需要在 “application-prod.yml ” 
	wjj.worker.easyfood 节点配置相关信息即可
	
<img width="732" alt="image" src="https://user-images.githubusercontent.com/54296655/163425695-022c7968-a538-438b-92b6-38b11f2f5019.png">

**Comment by beergold** [comment]
苹果/安卓 有很多方式抓包 可自行百度
相对简单些

**Comment by beergold** [comment]
如果不会抓包的兄弟太多了的话，后期会考虑输入账户信息自行模拟登录

**Comment by beergold** [comment]
还有就是文档中也特殊表明了，token有效期一般在两天超时请自行更换，你抓包时可以检索关键词如点击购物车后 检索 cart/index 类的
拿到token 和 userId

**Comment by beergold** [comment]
url 不需要变，只需要在配置文件中配置对应相关信息即可，其他都可以不用动

**Comment by NeelyYu** [comment]
昨晚太困，先睡觉了，感谢回答。
今天又试了下运行程序，跟了下断点。确定昨天的问题是我抓的token过期了，原因应该跟我切换全局的科学上网有关系。刚才已经正常跑起来了。原来token的验证是放在请求头里的，没注意，以为查询地址的请求也要拼什么参数，看你代码里没有拼接。
