### ISSUE TITLE
感谢作者大大！有一些疑问想请教下

### ISSUE THREAD

**Issue by ProdigalWang** [beergold/easyfood#3]
6点多买到了部分吃的，但是也遇到了一情况麻烦作者看看正常吗？

1. 6点前的预热会一直报  抢菜失败。。快去看下原因！！！！！NOTE_ORDER_SPECIAL-暂未营业，请6点后再试。-5014 
2. 6点左右开始抢菜的时候很多  {"msg":"","code":"-3001"} 日志 
3. 抢菜途中  商品信息有变化，请重新下单  是什么情况？要人工介入？
4. 还有抢菜途中 商品失效，会自动处理吗？
5. 暂停一个正在运行的任务时，代码报错 
```
The error may involve com.wjj.worker.persistence.dao.WJobDao.updateJob-Inline
### The error occurred while setting parameters
### SQL: UPDATE schedule_job_list 6点至7点 每隔一秒执行一次          SET SJL_ENABLE=?          where SJL_TASK_NAME=? and SJL_TASK_GROUP=?
### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '每隔一秒执行一次
         SET SJL_ENABLE=0 
        where SJL_TASK_NAME=' at line 1
```

**Comment by beergold** [comment]
1. 目前提前预热，将提前 购物车商品及 配送时间 缓存起来用于解决高峰期的流量剧增导致限流，所以因为目前提示6点营业说明已经缓存，这个后面可优化下，第一种属于正常情况，可以不用理会（建议不要关闭）
2. 由于流量剧增限流触发，可具体根据后台日志排查（请提供更详细的日志）
3. 这个分两种情况
	3.1 第一由于历史商品突然有货导致原缓存失效，程序将删除缓存用于二次下单（此处需抢购中检查是否全选购物车）
	3.2 购物车未发生任何变更或商品信息发生缺货或部分行为（这种情况无需处理，程序会自动响应）
4. 商品生效/缺货/售罄 及价格变更等都有可能会触发 问题3 会自动触发响应机制会有相对应的处理，无需人工介入
5. 已修复，请update

**Comment by ProdigalWang** [comment]
好的，感谢！回复的好详细，赞！
1.日志截图
![image](https://user-images.githubusercontent.com/20033998/163746689-a0c785a1-0a19-44df-a833-5c51961eab27.png)
2. 日志截图
![image](https://user-images.githubusercontent.com/20033998/163746863-d5d4a22e-15b8-4ee3-9ddd-58928f5ef706.png)
3.不需要自己先全选购物车是吗？有货会自动全选的意思？

**Comment by beergold** [comment]
1.图中情况无需而外处理，后续将优化下通知体验
2.确认下大概持续时间
3.目前仍然需要手动全选购物车，下个版本将自动勾选

另外特别说明（默认的定时不了解的情况下不要触碰）
由于抢菜过程中由于流量限制，会尝试一小时的发送尽最大可能抢菜
换句话来说可能别人还在选地址（限流，未返回地址），你已经在疯狂多线程下单了

**Comment by ProdigalWang** [comment]
第2点 {"msg":"","code":"-3001"} 日志 我这边从  05:42开始偶发
之后从 05:55~06:06 基本都是这个日志

**Comment by beergold** [comment]
不频繁的话暂时不用考虑，大概率限流了

**Comment by ProdigalWang** [comment]
预热往后延迟的话是不是概率会小一些？

**Comment by beergold** [comment]
延后订单的实效性就保证不了了，目前20秒已经很长了
