### ISSUE TITLE
叮咚更新签名算法了，作者能不能更新下代码

### ISSUE THREAD

**Issue by HowardLeo505** [beergold/easyfood#4]
叮咚更新签名算法了，算法其他好多程序已经跟进了，作者能不能跟进下这个程序的签名算法，主要只有这个程序自动化做的比较好，也有完整的前端，维护起来就方便点，可以的话先谢过作者了...

**Comment by beergold** [comment]
昨天check了下修复了，还没push，今晚十点左右我push，感谢支持

**Comment by beergold** [comment]
已修复，请update最新版本

**Comment by HowardLeo505** [comment]
好的，谢谢老哥，老哥牛逼！
