### ISSUE TITLE
没事了

### ISSUE THREAD

**Issue by chenshi1324** [beergold/easyfood#5]

**Comment by beergold** [comment]
有什么问题吗是，一直在忙没看到

**Comment by chenshi1324** [comment]
> 有什么问题吗，一直在忙没看到
小白 只会用现成的jar包 想请您帮忙弄一个来着的 之前用过别的脚本是yaml配置设置然后java -jar 运行 所以这个看不太懂  家里物资只剩面条了 ):

**Comment by chenshi1324** [comment]
> 有什么问题吗是，一直在忙没看到

刚刚自己运行了一下 表应该是建好了的 jar包打包好了
报了一个这个错 
![image](https://user-images.githubusercontent.com/60893309/165425905-16d5bce1-7c51-492f-b368-024d383dd167.png)

![image](https://user-images.githubusercontent.com/60893309/165425885-328df180-9961-4531-8417-418ec663267d.png)

**Comment by beergold** [comment]
端口号默认6379，redis弄个按时的就行

**Comment by beergold** [comment]
yaml和yml 配置上其实是差不多的，写法是一致的

**Comment by chenshi1324** [comment]
> 端口号默认6379，redis弄个按时的就行

要去哪里配置呀

**Comment by chenshi1324** [comment]
> 端口号默认6379，redis弄个按时的就行

我开了本地redis 是6379
![image](https://user-images.githubusercontent.com/60893309/165427561-e7fa26f5-8ace-4559-a05a-a6729f95c91d.png)

**Comment by beergold** [comment]
需要在application-prod中spring:redis:port中一栏配置

**Comment by beergold** [comment]
需要在application-prod中spring:redis:port中一栏配置

**Comment by chenshi1324** [comment]
> 需要在application-prod中spring:redis:port中一栏配置
项目已经跑起来了 这个cookie 在哪里填😂
有找到这个
![image](https://user-images.githubusercontent.com/60893309/165430526-ab78c57d-769b-4242-b3cf-32007d00317d.png)
下面两个我都明白 但是addressKeyWord这个是怎么填

**Comment by beergold** [comment]
地址的门牌号字段模糊搜索的

**Comment by beergold** [comment]
对应叮咚买菜内的，比如上海市黄浦区 门牌号填写 xx小区11号楼666
那只需要输入个关键词例如11号楼666
或者xx小区类似的

**Comment by chenshi1324** [comment]
> 对应叮咚买菜内的，比如上海市黄浦区 门牌号填写 xx小区11号楼666 那只需要输入个关键词例如11号楼666 或者xx小区类似的

好的  谢谢哈 幸苦了
