### ISSUE TITLE
叮咚更新了小程序 请问这个目前可用吗

### ISSUE THREAD

**Issue by cxjnevergiveup** [beergold/easyfood#7]

**Comment by beergold** [comment]
何出此言啊？当然可用啊
![image](https://user-images.githubusercontent.com/54296655/165649008-5e8ab120-c307-4546-ae87-b348fba50896.png)

**Comment by cxjnevergiveup** [comment]
> 何出此言啊？当然可用啊
> 
> ![image](https://user-images.githubusercontent.com/54296655/165649008-5e8ab120-c307-4546-ae87-b348fba50896.png)
> 
> 

隔壁Java的那个不能用了 今天8点30试试这个 谢谢大佬

**Comment by beergold** [comment]
嗯嗯没事，这不是隔壁嘛，每个人代码写的都不一，我这容错考虑的多

**Comment by cxjnevergiveup** [comment]
> 嗯嗯没事，这不是隔壁嘛，每个人代码写的都不一，我这容错考虑的多

大佬这个直接用idea可以运行吗 那个创建主表是干嘛的 还要操作数据库嘛

**Comment by beergold** [comment]
定时任务持久化

**Comment by beergold** [comment]
这程序初衷是极大减少手工操作的
你只需要配置好相关信息，前天晚上把菜选好，全选购物车睡觉去就得了
第二天早起付款就完了

**Comment by beergold** [comment]
还有问题吗？没有问题就close喽
